alias update="pass mahzen/sudo | sudo -S apt update; sudo apt full-upgrade"
alias my="cd ~/git/research/; pipenv run ipython -i ~/dev/libs.py"
alias weather="curl 'wttr.in/?m'"
alias crane="ssh -A hdogan@crane.unl.edu"
alias rhino="ssh -A hdogan@rhino.unl.edu"
alias panda="ssh -A haluk@sbbi-panda.unl.edu"
alias falcon="ssh -At haluk@sbbi-falcon.unl.edu zsh"
alias cse="ssh -A hdogan@cse.unl.edu"
